name: CI

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Vitest UI Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run Vitest tests
      run: |
        npm ci
        npm test -- --passWithNoTests
