name: Build Docker image

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - 'release/*'

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run Vitest tests
      run: |
        npm ci
        npm test -- --passWithNoTests

  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t owprov-ui:latest .

  trigger-deploy-to-dev:
    name: Trigger deployment
    runs-on: ubuntu-latest
    if: false
    needs:
      - docker
    steps:
    - name: Checkout actions repo
      uses: actions/checkout@v3
      with:
        repository: Telecominfraproject/.github
        path: github

    - name: Trigger deployment of the latest version to dev instance and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ucentralgw-dev-deployment.yaml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"force_latest": "true"}'
